// One autogenerated sidebar over the whole docs tree. Category order and labels come from each
// folder's _category_.json; page order within a category comes from sidebar_position frontmatter.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
